name: otaku_katarougu_app
description: A catalogue app for geeks.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_strategy: ^0.2.0
  responsive_builder: ^0.7.0
  flutter_animate: ^4.1.1+1
  google_maps_flutter: ^2.1.12
  google_maps_flutter_web: ^0.4.0+7
  http: ^0.13.3
  intl: ^0.17.0
  multiple_result: ^4.0.0
  font_awesome_flutter: ^10.5.0
  url_launcher: ^6.1.14
  fluttertoast: ^8.2.2
  geocoding: ^2.1.0
  geolocator: ^10.0.1
  image_picker: ^1.0.4
  google_fonts: ^4.0.4
  flutter_widget_from_html_core: ^0.10.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  loading_indicator: ^3.1.1
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0


dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/logo/logo_dark.png
    - assets/logo/logo_white.png