// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXASFhunJh1WjJKwVJln62kLqbej7DOd8',
    appId: '1:156674788109:web:7f49be89dcb06b7d3c7e44',
    messagingSenderId: '156674788109',
    projectId: 'otaku-katarougu',
    authDomain: 'otaku-katarougu.firebaseapp.com',
    storageBucket: 'otaku-katarougu.appspot.com',
    measurementId: 'G-X57CTDGPMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaLA_J931fmetc0Trebzxq_d5frwRwe6k',
    appId: '1:156674788109:android:8f761f0aae1b535f3c7e44',
    messagingSenderId: '156674788109',
    projectId: 'otaku-katarougu',
    storageBucket: 'otaku-katarougu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz175-jLLD0I6-zFR0KrXaTZoYFbPrGrU',
    appId: '1:156674788109:ios:45662e1acf72ac913c7e44',
    messagingSenderId: '156674788109',
    projectId: 'otaku-katarougu',
    storageBucket: 'otaku-katarougu.appspot.com',
    iosBundleId: 'com.otakuKatarouguApp',
  );
}
